CREATE TABLE products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    upc bigint NOT NULL,
    item_data text NOT NULL,
    BCItemBody text DEFAULT NULL,
    BCImageBody text DEFAULT NULL,
    BCItmID INTEGER DEFAULT NULL,
    itemAdded boolean NOT NULL DEFAULT false,
    imgAdded boolean NOT NULL DEFAULT false,
    UNIQUE (upc)
)