CREATE TABLE inventory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    in_stock boolean NOT NULL DEFAULT false,
    stock_level bigint DEFAULT NULL,
    upc_id int REFERENCES upcs (upc_id) ON DELETE CASCADE
)